let posts = [
  {
    postId: 1,
    title: "Title #1",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus mattis molestie a iaculis at erat pellentesque. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Imperdiet sed euismod nisi porta. Placerat duis ultricies lacus sed turpis tincidunt. Nunc lobortis mattis aliquam faucibus. Platea dictumst vestibulum rhoncus est. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Ullamcorper dignissim cras tincidunt lobortis feugiat. Non quam lacus suspendisse faucibus. Amet purus gravida quis blandit turpis cursus in. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Nec ultrices dui sapien eget. Posuere morbi leo urna molestie at. Consequat interdum varius sit amet mattis vulputate enim nulla. Varius quam quisque id diam vel quam. Massa tincidunt nunc pulvinar sapien et ligula.",
  },
  {
    postId: 2,
    title: "Title #2",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Sit amet volutpat consequat mauris nunc congue. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Urna duis convallis convallis tellus. Non sodales neque sodales ut etiam sit amet nisl. Justo laoreet sit amet cursus. Est ultricies integer quis auctor elit sed vulputate mi. Justo nec ultrices dui sapien eget mi. Tincidunt tortor aliquam nulla facilisi. Dictum varius duis at consectetur lorem donec massa. Risus nec feugiat in fermentum posuere urna. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Magna sit amet purus gravida.
Non odio euismod lacinia at quis risus sed vulputate. A diam maecenas sed enim. Nullam non nisi est sit amet. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Est sit amet facilisis magna etiam tempor orci eu lobortis. Nibh sed pulvinar proin gravida. Pellentesque id nibh tortor id aliquet. Elit eget gravida cum sociis. Magna eget est lorem ipsum dolor sit amet. A scelerisque purus semper eget duis at tellus. Arcu bibendum at varius vel pharetra vel. Volutpat ac tincidunt vitae semper quis. Elit at imperdiet dui accumsan. Blandit cursus risus at ultrices. Purus sit amet volutpat consequat mauris nunc. Ut pharetra sit amet aliquam id. Facilisis volutpat est velit egestas. Velit egestas dui id ornare arcu odio ut.`,
  },
  {
    postId: 3,
    title: "Title #3",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Quam viverra orci sagittis eu volutpat odio facilisis. Id porta nibh venenatis cras sed felis. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Iaculis nunc sed augue lacus viverra vitae congue. Elementum nisi quis eleifend quam. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Eu volutpat odio facilisis mauris sit amet. Morbi tincidunt augue interdum velit euismod. Hendrerit dolor magna eget est lorem ipsum dolor. Lectus quam id leo in vitae turpis. Auctor elit sed vulputate mi. Purus semper eget duis at. Sociis natoque penatibus et magnis dis parturient. Non curabitur gravida arcu ac tortor dignissim. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Velit scelerisque in dictum non consectetur a erat nam at.

Id semper risus in hendrerit. Bibendum enim facilisis gravida neque convallis a. Morbi enim nunc faucibus a pellentesque sit amet porttitor eget. Sem fringilla ut morbi tincidunt augue interdum velit euismod in. Ultricies tristique nulla aliquet enim tortor at. Id venenatis a condimentum vitae sapien. Eget est lorem ipsum dolor sit amet consectetur adipiscing. Arcu ac tortor dignissim convallis aenean et tortor. Nibh sit amet commodo nulla. Sed pulvinar proin gravida hendrerit lectus. Odio ut sem nulla pharetra diam sit amet. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Tortor id aliquet lectus proin.
    
Duis convallis convallis tellus id interdum. Sed pulvinar proin gravida hendrerit lectus a. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Sed velit dignissim sodales ut eu sem. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. In fermentum posuere urna nec tincidunt praesent semper feugiat. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. At elementum eu facilisis sed odio morbi quis commodo odio. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. At auctor urna nunc id cursus metus aliquam eleifend. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Sed cras ornare arcu dui vivamus arcu felis. Semper auctor neque vitae tempus quam. Egestas dui id ornare arcu odio.`,
  },
];
exports.posts = posts;
exports.postId = posts.length;

exports.homeStartingContent =
  "Lacus vel facilisis volutpat est velit egestas dui id ornare. Semper auctor neque vitae tempus quam. Sit amet cursus sit amet dictum sit amet justo. Viverra tellus in hac habitasse. Imperdiet proin fermentum leo vel orci porta. Donec ultrices tincidunt arcu non sodales neque sodales ut. Mattis molestie a iaculis at erat pellentesque adipiscing. Magnis dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Odio euismod lacinia at quis risus sed vulputate odio ut. Cursus mattis molestie a iaculis at erat pellentesque adipiscing.";
exports.aboutContent =
  "Hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Non diam phasellus vestibulum lorem sed. Platea dictumst quisque sagittis purus sit. Egestas sed sed risus pretium quam vulputate dignissim suspendisse. Mauris in aliquam sem fringilla. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Amet massa vitae tortor condimentum lacinia quis vel eros. Enim ut tellus elementum sagittis vitae. Mauris ultrices eros in cursus turpis massa tincidunt dui.";
exports.contactContent =
  "Scelerisque eleifend donec pretium vulputate sapien. Rhoncus urna neque viverra justo nec ultrices. Arcu dui vivamus arcu felis bibendum. Consectetur adipiscing elit duis tristique. Risus viverra adipiscing at in tellus integer feugiat. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Consequat interdum varius sit amet mattis. Iaculis nunc sed augue lacus. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Pulvinar elementum integer enim neque. Ultrices gravida dictum fusce ut placerat orci nulla. Mauris in aliquam sem fringilla ut morbi tincidunt. Tortor posuere ac ut consequat semper viverra nam libero.";
